jobs:
  include:
    - language: java
      install: true
      jdk:
        - oraclejdk8
      script:
        - cd backend
        - ./gradlew clean build
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - language: node_js
      node_js:
        - "8"
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        directories:
          - ./node_modules
      script:
        - cd frontend
        - npm install
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
        - npm run compodoc
      before_deploy:
        - cd frontend
        - npm build
        - cd ..
        - cd backend
        - ./gradlew build
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: "backend/build/libs/*"
          skip_cleanup: true
          on:
            tags: true
            branch: master